<?php

/**
 * @file
 * Conditional logic and data processing for HDYWDT.
 */

/**
 * Load hdywtdt's include files for theme processing.
 */
include_once 'includes/preprocess.inc';
include_once 'includes/process.inc';
include_once 'includes/theme.inc';
include_once 'includes/alter.inc';

function hdywtdt_preprocess_patterns_overview_page(array &$variables) {
  // Sort alphabetically in ascending order.
  ksort($variables['patterns']);
}
